<h2>Edit a country</h2>
<?php if (isset($this->alert) && !empty($this->alert)): ?>
	<section class="popup">
		<div class="alert alert-<?php echo $this->alert['type']; ?> alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
					aria-hidden="true">x</span></button>
			<?php echo $this->alert['content']; ?>
		</div>
	</section>
<?php endif; ?>
<section class="country">
	<p>
		<?php
			$form = $this->countryForm;
			$form->setAttribute("class", "form-vertical");
			$form->setAttribute('action', $this->url(null, [
				'action' => 'processEdit',
			]));
			$form->prepare();
			echo $this->form()->render($form);
		?>
	</p>
	<a href="<?php echo $this->url('apic-admin'); ?>"> << Retour à l'accueil</a>
</section>